### ISSUE TITLE
'facter --yaml' on stock debian install outputs garbage

### ISSUE THREAD

**Issue by timlnx** [RHInception/jsonstats#17]
``` yaml
root@ip-:~# facter --yaml 2>&1 | head
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
--- 
  architecture: amd64
  arp: "fe:ff:ff:ff:ff:ff"
  kernel: Linux
  arp_eth0: "fe:ff:ff:ff:ff:ff"
  domain: ec2.internal
  macaddress: "22:00:0a:47:8f:a9"
```

See that second line there? About ruby?

Yeah. Because we're using `commands.getstatusoutput` (not negotiable, it's for backwards compatibility) we're getting the `stdout` **and** the `stderr` in the result from our `_exec` call in the Facter plugin.
